server:
    port: 8824
spring:
    application:
        name: common-util-service
    redis:
        cluster:
            max-redirects: 3
            nodes: xxxxxx
        database: 14
        lettuce:
            pool:
                max-active: 8
                max-idle: 5
                max-wait: 10000ms
                min-idle: 1
            shutdown-timeout: 100ms
        timeout: 3000ms
        password: qwe123$%^
